kabi 1

diff --git a/.github/actions/action.yml b/.github/actions/action.yml
--- a/.github/actions/action.yml
+++ b/.github/actions/action.yml
@@ -1139,46 +1139,46 @@ runs:
         echo "✅ KSU hooks applied"
         echo "::endgroup::"
 
-    - name: Apply Other Patches
-      shell: bash
-      run: |
-        set -euo pipefail
-        echo "::group::Apply Other patches"
-        cd "$COMMON_KERNEL_FOLDER"
-        KERNEL_VERSION="${{ env.KERNEL_VER }}"
-        MIN_VERSION="5.16"
-        if [ "$(printf '%s\n' "$KERNEL_VERSION" "$MIN_VERSION" | sort -V | head -n1)" = "$KERNEL_VERSION" ]; then
-          echo "Patching ptrace!"
-          patch -p1 -F 3 < "$KERNEL_PATCHES_FOLDER/gki_ptrace.patch"
-        else
-          echo "Kernel >= $MIN_VERSION, skipping ptrace patch"
-        fi
-        if [ "$OP_HMBIRD" = true ]; then
-          echo "Patching hmbird!"
-          dos2unix "$KERNEL_PATCHES_FOLDER/oneplus/hmbird/fengchi_${OP_MODEL}_${OP_OS_VERSION}.patch"
-          patch -p1 -F 3 < "$KERNEL_PATCHES_FOLDER/oneplus/hmbird/fengchi_${OP_MODEL}_${OP_OS_VERSION}.patch"
-          dos2unix "$KERNEL_PATCHES_FOLDER/oneplus/hmbird/overwriter.patch"
-          patch -p1 -F 3 < "$KERNEL_PATCHES_FOLDER/oneplus/hmbird/overwriter.patch"
-          chmod +x ./drivers/of/overwriter/overwrite_configs/convert_configs.sh
-          dos2unix "$KERNEL_PATCHES_FOLDER/oneplus/hmbird/hmbird_config.patch"
-          patch -p1 -F 3 < "$KERNEL_PATCHES_FOLDER/oneplus/hmbird/hmbird_config.patch"
-        else
-          echo "Hmbird not enabled, skipping fengchi patch"
-        fi
+    # - name: Apply Other Patches
+      # shell: bash
+      # run: |
+        # set -euo pipefail
+        # echo "::group::Apply Other patches"
+        # cd "$COMMON_KERNEL_FOLDER"
+        # KERNEL_VERSION="${{ env.KERNEL_VER }}"
+        # MIN_VERSION="5.16"
+        # if [ "$(printf '%s\n' "$KERNEL_VERSION" "$MIN_VERSION" | sort -V | head -n1)" = "$KERNEL_VERSION" ]; then
+          # echo "Patching ptrace!"
+          # patch -p1 -F 3 < "$KERNEL_PATCHES_FOLDER/gki_ptrace.patch"
+        # else
+          # echo "Kernel >= $MIN_VERSION, skipping ptrace patch"
+        # fi
+        # if [ "$OP_HMBIRD" = true ]; then
+          # echo "Patching hmbird!"
+          # dos2unix "$KERNEL_PATCHES_FOLDER/oneplus/hmbird/fengchi_${OP_MODEL}_${OP_OS_VERSION}.patch"
+          # patch -p1 -F 3 < "$KERNEL_PATCHES_FOLDER/oneplus/hmbird/fengchi_${OP_MODEL}_${OP_OS_VERSION}.patch"
+          # dos2unix "$KERNEL_PATCHES_FOLDER/oneplus/hmbird/overwriter.patch"
+          # patch -p1 -F 3 < "$KERNEL_PATCHES_FOLDER/oneplus/hmbird/overwriter.patch"
+          # chmod +x ./drivers/of/overwriter/overwrite_configs/convert_configs.sh
+          # dos2unix "$KERNEL_PATCHES_FOLDER/oneplus/hmbird/hmbird_config.patch"
+          # patch -p1 -F 3 < "$KERNEL_PATCHES_FOLDER/oneplus/hmbird/hmbird_config.patch"
+        # else
+          # echo "Hmbird not enabled, skipping fengchi patch"
+        # fi
         
-        patch -p1 --forward < "$KERNEL_PATCHES_FOLDER/common/optimized_mem_operations.patch"
-        patch -p1 --forward < "$KERNEL_PATCHES_FOLDER/common/file_struct_8bytes_align.patch"
-        patch -p1 --forward < "$KERNEL_PATCHES_FOLDER/common/reduce_cache_pressure.patch"
+        # patch -p1 --forward < "$KERNEL_PATCHES_FOLDER/common/optimized_mem_operations.patch"
+        # patch -p1 --forward < "$KERNEL_PATCHES_FOLDER/common/file_struct_8bytes_align.patch"
+        # patch -p1 --forward < "$KERNEL_PATCHES_FOLDER/common/reduce_cache_pressure.patch"
         
-        patch -p1 --forward < "$KERNEL_PATCHES_FOLDER/common/mem_opt_prefetch.patch"
+        # patch -p1 --forward < "$KERNEL_PATCHES_FOLDER/common/mem_opt_prefetch.patch"
         
-        if [ "$(printf '%s\n' "$KERNEL_VERSION" "$MIN_VERSION" | sort -V | tail -n1)" = "$KERNEL_VERSION" ]; then
-          patch -p1 --forward < "$KERNEL_PATCHES_FOLDER/common/optimise_memcmp.patch"
-        elif [ "$(printf '%s\n' "$KERNEL_VERSION" "5.11" | sort -V | tail -n1)" = "$KERNEL_VERSION" ]; then
-          sed -e 's/SYM_FUNC_START(__pi_memcmp)/SYM_FUNC_START_WEAK_PI(memcmp)/' -e 's/SYM_FUNC_END(__pi_memcmp)/SYM_FUNC_END_PI(memcmp)/' -e 's/SYM_FUNC_ALIAS_WEAK(memcmp, __pi_memcmp)/EXPORT_SYMBOL_NOKASAN(memcmp)/' "$KERNEL_PATCHES_FOLDER/common/optimise_memcmp.patch" | patch -p1 --forward
-        else
-          echo "Optimised memcmp patch not found!"
-        fi
+        # if [ "$(printf '%s\n' "$KERNEL_VERSION" "$MIN_VERSION" | sort -V | tail -n1)" = "$KERNEL_VERSION" ]; then
+          # patch -p1 --forward < "$KERNEL_PATCHES_FOLDER/common/optimise_memcmp.patch"
+        # elif [ "$(printf '%s\n' "$KERNEL_VERSION" "5.11" | sort -V | tail -n1)" = "$KERNEL_VERSION" ]; then
+          # sed -e 's/SYM_FUNC_START(__pi_memcmp)/SYM_FUNC_START_WEAK_PI(memcmp)/' -e 's/SYM_FUNC_END(__pi_memcmp)/SYM_FUNC_END_PI(memcmp)/' -e 's/SYM_FUNC_ALIAS_WEAK(memcmp, __pi_memcmp)/EXPORT_SYMBOL_NOKASAN(memcmp)/' "$KERNEL_PATCHES_FOLDER/common/optimise_memcmp.patch" | patch -p1 --forward
+        # else
+          # echo "Optimised memcmp patch not found!"
+        # fi
         # patch -p1 --forward < "$KERNEL_PATCHES_FOLDER/common/minimise_wakeup_time.patch"
         # patch -p1 --forward < "$KERNEL_PATCHES_FOLDER/common/int_sqrt.patch"
         # patch -p1 --forward < "$KERNEL_PATCHES_FOLDER/common/force_tcp_nodelay.patch"
@@ -1187,11 +1187,11 @@ runs:
         # patch -p1 --forward < "$KERNEL_PATCHES_FOLDER/common/f2fs_reduce_congestion.patch"
         # patch -p1 --forward < "$KERNEL_PATCHES_FOLDER/common/reduce_freeze_timeout.patch"
         
-        if [ "$(printf '%s\n' "$KERNEL_VERSION" "$MIN_VERSION" | sort -V | head -n1)" = "$KERNEL_VERSION" ]; then
-          patch -p1 --forward < "$KERNEL_PATCHES_FOLDER/common/clear_page_16bytes_align.patch"
-        else
-          cat "$KERNEL_PATCHES_FOLDER/common/clear_page_16bytes_align.patch" | sed -e 's/SYM_FUNC_START_PI(clear_page)/SYM_FUNC_START_PI(__pi_clear_page)/' | patch -p1 -F3 --forward
-        fi
+        # if [ "$(printf '%s\n' "$KERNEL_VERSION" "$MIN_VERSION" | sort -V | head -n1)" = "$KERNEL_VERSION" ]; then
+          # patch -p1 --forward < "$KERNEL_PATCHES_FOLDER/common/clear_page_16bytes_align.patch"
+        # else
+          # cat "$KERNEL_PATCHES_FOLDER/common/clear_page_16bytes_align.patch" | sed -e 's/SYM_FUNC_START_PI(clear_page)/SYM_FUNC_START_PI(__pi_clear_page)/' | patch -p1 -F3 --forward
+        # fi
         
         
         # echo "Patching add_limitation_scaling_min_freq.patch"
@@ -1219,8 +1219,8 @@ runs:
         # echo "Patching use_unlikely_wrap_cpufreq.patch"
         # patch -p1 -F3 --forward < "$KERNEL_PATCHES_FOLDER/common/use_unlikely_wrap_cpufreq.patch"
         
-        echo "✅ Other patches applied"
-        echo "::endgroup::"
+        # echo "✅ Other patches applied"
+        # echo "::endgroup::"
 
     - name: Apply Unicode Fix Patch
       shell: bash
@@ -1275,45 +1275,45 @@ runs:
         CONFIG_IP6_NF_MATCH_HL=y
         EOF
 
-    - name: Add IP SET & IPv6_NAT Support
-      if: ${{ env.OP_IP_SET == 'true' }}
-      shell: bash
-      run: |
-        set -euo pipefail
-        echo "Add IP SET & IPv6_NAT Support"
-        cd "$COMMON_KERNEL_FOLDER"
-        KERNEL_VERSION="${{ env.KERNEL_VER }}"
+    # - name: Add IP SET & IPv6_NAT Support
+      # if: ${{ env.OP_IP_SET == 'true' }}
+      # shell: bash
+      # run: |
+        # set -euo pipefail
+        # echo "Add IP SET & IPv6_NAT Support"
+        # cd "$COMMON_KERNEL_FOLDER"
+        # KERNEL_VERSION="${{ env.KERNEL_VER }}"
         
-        if [[ "$KERNEL_VERSION" != "6.12" ]] || [[ "$OP_BRANCH" != wild/mt* ]]; then
-            echo "CONFIG_BPF_STREAM_PARSER=y" >> "$COMMON_KERNEL_FOLDER/arch/arm64/configs/gki_defconfig"
-        fi
+        # if [[ "$KERNEL_VERSION" != "6.12" ]] || [[ "$OP_BRANCH" != wild/mt* ]]; then
+            # echo "CONFIG_BPF_STREAM_PARSER=y" >> "$COMMON_KERNEL_FOLDER/arch/arm64/configs/gki_defconfig"
+        # fi
         
-        cat >> "$COMMON_KERNEL_FOLDER/arch/arm64/configs/gki_defconfig" <<EOF
-        CONFIG_IP_SET=y
-        CONFIG_IP_SET_MAX=65534
-        CONFIG_IP_SET_BITMAP_IP=y
-        CONFIG_IP_SET_BITMAP_IPMAC=y
-        CONFIG_IP_SET_BITMAP_PORT=y
-        CONFIG_IP_SET_HASH_IP=y
-        CONFIG_IP_SET_HASH_IPMARK=y
-        CONFIG_IP_SET_HASH_IPPORT=y
-        CONFIG_IP_SET_HASH_IPPORTIP=y
-        CONFIG_IP_SET_HASH_IPPORTNET=y
-        CONFIG_IP_SET_HASH_IPMAC=y
-        CONFIG_IP_SET_HASH_MAC=y
-        CONFIG_IP_SET_HASH_NETPORTNET=y
-        CONFIG_IP_SET_HASH_NET=y
-        CONFIG_IP_SET_HASH_NETNET=y
-        CONFIG_IP_SET_HASH_NETPORT=y
-        CONFIG_IP_SET_HASH_NETIFACE=y
-        CONFIG_IP_SET_LIST_SET=y
-        CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y
-        CONFIG_NETFILTER_XT_SET=y
-        CONFIG_IP6_NF_NAT=y
-        CONFIG_IP6_NF_TARGET_MASQUERADE=y
-        EOF
+        # cat >> "$COMMON_KERNEL_FOLDER/arch/arm64/configs/gki_defconfig" <<EOF
+        # CONFIG_IP_SET=y
+        # CONFIG_IP_SET_MAX=65534
+        # CONFIG_IP_SET_BITMAP_IP=y
+        # CONFIG_IP_SET_BITMAP_IPMAC=y
+        # CONFIG_IP_SET_BITMAP_PORT=y
+        # CONFIG_IP_SET_HASH_IP=y
+        # CONFIG_IP_SET_HASH_IPMARK=y
+        # CONFIG_IP_SET_HASH_IPPORT=y
+        # CONFIG_IP_SET_HASH_IPPORTIP=y
+        # CONFIG_IP_SET_HASH_IPPORTNET=y
+        # CONFIG_IP_SET_HASH_IPMAC=y
+        # CONFIG_IP_SET_HASH_MAC=y
+        # CONFIG_IP_SET_HASH_NETPORTNET=y
+        # CONFIG_IP_SET_HASH_NET=y
+        # CONFIG_IP_SET_HASH_NETNET=y
+        # CONFIG_IP_SET_HASH_NETPORT=y
+        # CONFIG_IP_SET_HASH_NETIFACE=y
+        # CONFIG_IP_SET_LIST_SET=y
+        # CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y
+        # CONFIG_NETFILTER_XT_SET=y
+        # CONFIG_IP6_NF_NAT=y
+        # CONFIG_IP6_NF_TARGET_MASQUERADE=y
+        # EOF
         
-        patch -p1 -F 3 < "$KERNEL_PATCHES_FOLDER/common/IPv6_NAT_FIX.patch"
+        # patch -p1 -F 3 < "$KERNEL_PATCHES_FOLDER/common/IPv6_NAT_FIX.patch"
 
     - name: Add LXC / Droidspaces support
       shell: bash
@@ -1324,8 +1324,15 @@ runs:
         cd "$COMMON_KERNEL_FOLDER"
         
         echo "Applying patch to enable SYSVIPC without breaking ABI"
-        patch -p1 -F3 --forward < "$KERNEL_PATCHES_FOLDER/oneplus/lxc_droidspaces/enable_sysvipc.patch"
+        # patch -p1 -F3 --forward < "$KERNEL_PATCHES_FOLDER/oneplus/lxc_droidspaces/enable_sysvipc.patch"
         
+        # 1, 2, 3
+        curl -Ls https://github.com/nullptr-t-oss/android_kernel_common_oneplus_sm8550/commit/99c42c1cdec298a2c9fe35ca64712220eba9a151.patch | patch -p1 --forward
+        
+        # 3, 4, 5
+        # curl -Ls https://github.com/nullptr-t-oss/android_kernel_common_oneplus_sm8550/commit/99c42c1cdec298a2c9fe35ca64712220eba9a151.patch | patch -p1 --forward
+        
+        # 6, 7, 8
         # curl -Ls https://github.com/nullptr-t-oss/android_kernel_common_oneplus_sm8550/commit/99c42c1cdec298a2c9fe35ca64712220eba9a151.patch | patch -p1 --forward
         
         cat >> "$COMMON_KERNEL_FOLDER/arch/arm64/configs/gki_defconfig" <<EOF
